version: 2

run:
  timeout: 5m
  tests: true # проверки при тестах

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign

issues:
  exclude-use-default: false
  exclude:
    - "error return value not checked"